environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: Visual Studio 14 2015
      CXX_STANDARD: 11

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: Visual Studio 15 2017
      CXX_STANDARD: 14

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: Visual Studio 16 2019
      CXX_STANDARD: 17

install:
  - mkdir C:\LIB
  - mkdir C:\LIB\ICU
  - curl -fsSL -o C:\LIB\icu4c-bin.zip https://github.com/unicode-org/icu/releases/download/release-71-1/icu4c-71_1-Win64-MSVC2019.zip
  - 7z x C:\LIB\icu4c-bin.zip -oC:\LIB\ICU

before_build:
  - init.bat
  - mkdir build
  - cd build
  - cmake .. -G "%GENERATOR%" -A x64 -DCMAKE_CXX_STANDARD="%CXX_STANDARD%" -DICU_ROOT=C:\LIB\ICU

build_script:
  - cmake --build . --config Release

test_script:
  - set PATH=%PATH%;C:\LIB\ICU\bin64
  - ctest -C Release -V
