environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: Visual Studio 14 2015
      CXX_STANDARD: 11

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: Visual Studio 15 2017
      CXX_STANDARD: 14

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: Visual Studio 16 2019
      CXX_STANDARD: 17

install:
  - install-icu.bat C:\LIB 71

before_build:
  - init.bat
  - mkdir build
  - cd build
  - cmake .. -G "%GENERATOR%" -A x64 -DCMAKE_CXX_STANDARD="%CXX_STANDARD%" -DICU_ROOT=C:\LIB\ICU

build_script:
  - cmake --build . --config Release

test_script:
  - set PATH=%PATH%;C:\LIB\ICU\bin64
  - ctest -C Release -V
